# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Tools
      run: |
        dotnet tool restore
        dotnet paket restore
        npm install

    - name: Build
      run: |
        dotnet run --project Build.fsproj -- Build

    - name: Test
      run: |
        dotnet run --project Build.fsproj -- RunTestsHeadless
